#!/usr/bin/env bash
#
# render-pretty.sh — wrap a raw assessment.md with a reviewer-friendly header,
# auto-generated table of contents, severity legend, and footer checklist.
#
# Usage:
#   render-pretty.sh \
#       --assessment       <path-to-assessment.md> \
#       --target-slug      <owner__repo> \
#       --pr-url           <https://github.com/.../pull/N> \
#       --run-url          <https://github.com/.../actions/runs/N> \
#       --rubric-version   <commit-sha-or-version-string> \
#       --harness-repo-url <https://github.com/owner/harness-repo>
#
# Emits the polished Markdown to stdout. No external dependencies beyond
# bash + awk + sed. Designed to be deterministic so two runs against the
# same inputs produce byte-identical output.

set -euo pipefail

assessment=""
target_slug=""
pr_url=""
run_url=""
rubric_version=""
harness_repo_url=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --assessment)       assessment="$2";       shift 2 ;;
    --target-slug)      target_slug="$2";      shift 2 ;;
    --pr-url)           pr_url="$2";           shift 2 ;;
    --run-url)          run_url="$2";          shift 2 ;;
    --rubric-version)   rubric_version="$2";   shift 2 ;;
    --harness-repo-url) harness_repo_url="$2"; shift 2 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

for var in assessment target_slug pr_url run_url rubric_version harness_repo_url; do
  if [[ -z "${!var}" ]]; then
    echo "missing required arg --${var//_/-}" >&2
    exit 2
  fi
done

if [[ ! -f "$assessment" ]]; then
  echo "assessment not found: $assessment" >&2
  exit 2
fi

# Convert "owner__repo" → "owner/repo" for display.
target_display="${target_slug/__//}"
generated_at="$(date -u +'%Y-%m-%d %H:%M:%S UTC')"

# ----- Title block -----
cat <<EOF
# Assessment report — \`${target_display}\`

| Field | Value |
|-------|-------|
| Target repo | [\`${target_display}\`](https://github.com/${target_display}) |
| Source PR | ${pr_url} |
| Cloud Agent run | ${run_url} |
| Rubric version | \`${rubric_version}\` |
| Generated (UTC) | ${generated_at} |

> **Reviewer:** This document was produced by an automated Cloud Agent and
> validated against the harness rubric. Sample-verify cited files before
> sharing externally.

---

## Severity legend

| Symbol | Meaning |
|--------|---------|
| 🔴 | Critical — fix immediately, likely production impact |
| 🟠 | High — fix in current sprint |
| 🟡 | Medium — schedule within next planning cycle |
| 🟢 | Low — backlog / nice-to-have |
| ℹ️ | Informational — no action required |

---

## Table of contents

EOF

# ----- Table of contents (auto-generated from H1 + H2 headings) -----
#
# GitHub anchor convention: lowercase, spaces → hyphens, strip non-alphanumeric
# except hyphens. We mirror that to keep the links functional inside the
# polished file when viewed on github.com or rendered to HTML.

awk '
  # GitHub anchor convention: lowercase, drop non-alphanumeric (keep spaces
  # and hyphens), then convert each whitespace character to a single hyphen.
  # Note: do NOT collapse runs of whitespace — GitHub maps each space to its
  # own hyphen, so "A & B" becomes "a--b" (two hyphens).
  function slugify(s,    out) {
    out = tolower(s)
    gsub(/[^a-z0-9 \-]/, "", out)
    gsub(/[[:space:]]/, "-", out)
    return out
  }
  /^# [^#]/  { title = substr($0, 3); printf "- [%s](#%s)\n",   title, slugify(title); next }
  /^## [^#]/ { title = substr($0, 4); printf "  - [%s](#%s)\n", title, slugify(title) }
' "$assessment"

# ----- Body separator + raw assessment -----
cat <<'EOF'

---

## Assessment body

EOF

cat "$assessment"

# ----- Footer: reviewer checklist -----
cat <<'EOF'

---

## Reviewer checklist

Before merging the source PR or sharing this report with the application
team, confirm:

- [ ] All ten rubric sections are present and non-empty (the
      `finalize-assessment` workflow check should already be ✅).
- [ ] At least one cited file in the **Evidence** section was
      sample-verified by opening it in the target repository.
- [ ] No secrets, PII, or sensitive credentials are present in the
      assessment body. Redact and re-run if found.
- [ ] Severity gradings (🔴/🟠/🟡/🟢) feel calibrated against the
      operator's risk model.
- [ ] Findings have been routed to the right owners (e.g., security
      team, platform team, application team).
- [ ] Any items in **Coverage gaps** are acceptable for this batch, or
      a follow-up assessment has been scheduled.

EOF

# Footer line emitted separately so the heredoc above can stay
# single-quoted (the body contains markdown backticks that would
# otherwise be interpreted as command substitution).
printf '> Generated by the [code-assessment-harness](%s) finalize\n> workflow.\n' \
  "$harness_repo_url"
